// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hpceefnmrqwifgqwrkel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhwY2VlZm5tcnF3aWZncXdya2VsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxODg5MjAsImV4cCI6MjA2Mzc2NDkyMH0.lvGnN_Hw8HT8UVRkGU-5rKZkMBh9HKGSSGcJGd3Zdns";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);